Skip latest tag creation on develop branch
docksal/service-varnish pull request #22
Opened 2019-01-30 11:15 UTC by sergey-zabolotny

2019-01-30 16:40 UTC, lmakarov requested changes

2019-01-30 16:40 UTC, lmakarov commented on release.sh
> +		[[ "${TRAVIS_BRANCH}" == "develop" -a "${tag}" ~= "latest" ]] && continue
I think this should look like:

```
[[ "${TRAVIS_BRANCH}" == "develop" ]] && [[ "${tag}" =~ "latest" ]] && continue
```

2019-01-31 08:47 UTC, sergey-zabolotny commented on release.sh
> +		[[ "${TRAVIS_BRANCH}" == "develop" -a "${tag}" ~= "latest" ]] && continue
fixed

2019-01-31 19:16 UTC, lmakarov approved these changes

2019-01-31 19:16 UTC, merged